spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elm_business?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: business-service  # 自定义服务名
server:
    port: 8082
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
    register-with-eureka: true
    fetch-registry: true